version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: fast-api-app
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ./src/api:/app/src/api
    ports:
      - "8000:8000"
    restart: always
