version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: fast-api-app
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ./src:/app/src
    network_mode: "host"
    restart: always
